### ISSUE TITLE
Unnötiger Vergleich

### ISSUE THREAD

**Issue by behrends** [Gahstum/Quiz#8]
Die Methode `checkYesNo` liefert bereits ein `boolean`-Wert zurück, was den Vergleich überflüssig macht.

https://github.com/Gahstum/Quiz/blob/1fedb0f973c1be93acfc1d38960a7ea59714e886/src/Quiz.java#L25

(Dies wurde in IntelliJ mit `Analyze`>`Inspect Code…` gefunden)

**Comment by Gahstum** [comment]
Behandelt in c109eabedb3d7883fc22e06eca786fb4a5602beb
