### ISSUE TITLE
Einheitliche Sprache für Bezeichner

### ISSUE THREAD

**Issue by behrends** [Gahstum/Quiz#9]
Besser nur Englisch für Bezeichner verwenden als eine Mischung von beiden (`questions`/`topic` bzw. `thema`).

https://github.com/Gahstum/Quiz/blob/1fedb0f973c1be93acfc1d38960a7ea59714e886/src/Topic.java#L20-L30

**Comment by Gahstum** [comment]
Haben es korrigiert
